apiVersion: 1

deleteDatasources:
  - name: MongoDB
  - name: Prometheus

datasources:
  # Prometheus for system metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}
    version: 1

  # MongoDB datasource using the MongoDB plugin
  - name: MongoDB
    type: grafana-mongodb-datasource
    access: proxy
    url: mongodb://crypto_user:crypto_password@mongodb:27017/crypto_db
    database: crypto_db
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      authType: "credentials"
      defaultDatabase: "crypto_db"
    secureJsonData:
      username: "crypto_user"
      password: "crypto_password"
    version: 1

  # SimpleJSON datasource for custom API endpoints
  - name: Crypto API
    type: simplejson
    access: proxy
    url: http://airflow-webserver:8080
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      timeInterval: "30s"
    version: 1